version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dwayneward
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: todoist_db
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data:
